services:
  telemetry-simulator:
    build:
      context: ./services/telemetry-simulator/telemetry-simulator
      dockerfile: Dockerfile
    container_name: telemetry-simulator
    network_mode: host
    env_file: .env
  telemetry-services:
    build:
      context: ./services/telemetry-services/telemetry-services
      dockerfile: Dockerfile
    container_name: telemetry-services
    network_mode: host
    env_file: .env
  telemetry-client:
    build:
      context: ./clients/telemetry-client
      dockerfile: Dockerfile
    container_name: telemetry-client
    network_mode: host
    depends_on:
      - telemetry-services
      - telemetry-simulator
    restart: always
